P99: p99_futex::p99_futex_init
p99_futex_add
P99_FUTEX_COMPARE_EXCHANGE
p99_futex_destroy
p99_futex_exchange
p99_futex_init
p99_futex_load
P99_FUTEX_MAX_WAITERS
p99_futex_wait
p99_futex_wakeup
p99_futex_init()
p99_futex * p99_futex_init (p99_futex * p00_c, unsigned p00_ini) related
Initialize an p99_futex object.
Referenced by p99_cm::p99_cm_init(), p99_count_init(), p99_iterator::p99_iterator_init(), p99_notifier::p99_notifier_init(), and p99_rwl_init().