P99: p99_futex::p99_futex_destroy
p99_futex_add
P99_FUTEX_COMPARE_EXCHANGE
p99_futex_destroy
p99_futex_exchange
p99_futex_init
p99_futex_load
P99_FUTEX_MAX_WAITERS
p99_futex_wait
p99_futex_wakeup
p99_futex_destroy()
void p99_futex_destroy (p99_futex * p00_c) related
Destroy an p99_futex object.
Referenced by p99_cm::p99_cm_destroy(), p99_count_destroy(), p99_iterator::p99_iterator_destroy(), p99_notifier::p99_notifier_destroy(), and p99_rwl_destroy().