P99: p99_futex::p99_futex_load
p99_futex_add
P99_FUTEX_COMPARE_EXCHANGE
p99_futex_destroy
p99_futex_exchange
p99_futex_init
p99_futex_load
P99_FUTEX_MAX_WAITERS
p99_futex_wait
p99_futex_wakeup
p99_futex_load()
unsigned p99_futex_load (p99_futex volatile * p00_fut) related
Obtain the value of futex p00_fut atomically.
Referenced by p99_count::p99_count_value(), p99_notifier::p99_notifier_load(), and p99_rwl::p99_rwl_islocked().