/* This file is automatically generated, do not change manually. */
#define _ARG(\
	_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,\
	_9,	_10,	_11,	_12,	_13,	_14,	_15,	_16,\
	_17,	_18,	_19,	_20,	_21,	_22,	_23,	_24,\
	_25,	_26,	_27,	_28,	_29,	_30,	_31,	_32,\
	_33,	_34,	_35,	_36,	_37,	_38,	_39,	_40,\
	_41,	_42,	_43,	_44,	_45,	_46,	_47,	_48,\
	_49,	_50,	_51,	_52,	_53,	_54,	_55,	_56,\
	_57,	_58,	_59,	_60,	_61,	_62,	_63,	_64,\
	...) _64
#define _NARG_1(...) _ARG(__VA_ARGS__, \
	63,	62,	61,	60,	59,	58,	57,	56,\
	55,	54,	53,	52,	51,	50,	49,	48,\
	47,	46,	45,	44,	43,	42,	41,	40,\
	39,	38,	37,	36,	35,	34,	33,	32,\
	31,	30,	29,	28,	27,	26,	25,	24,\
	23,	22,	21,	20,	19,	18,	17,	16,\
	15,	14,	13,	12,	11,	10,	9,	8,\
	7,	6,	5,	4,	3,	2,	1,	0,)
#define _NARG_2(...) _ARG(__VA_ARGS__, \
	_INV(2),	31,	_INV(2),	30,	_INV(2),	29,	_INV(2),	28,\
	_INV(2),	27,	_INV(2),	26,	_INV(2),	25,	_INV(2),	24,\
	_INV(2),	23,	_INV(2),	22,	_INV(2),	21,	_INV(2),	20,\
	_INV(2),	19,	_INV(2),	18,	_INV(2),	17,	_INV(2),	16,\
	_INV(2),	15,	_INV(2),	14,	_INV(2),	13,	_INV(2),	12,\
	_INV(2),	11,	_INV(2),	10,	_INV(2),	9,	_INV(2),	8,\
	_INV(2),	7,	_INV(2),	6,	_INV(2),	5,	_INV(2),	4,\
	_INV(2),	3,	_INV(2),	2,	_INV(2),	1,	_INV(2),	0,)
#define _NARG_3(...) _ARG(__VA_ARGS__, \
	21,	_INV(3),	_INV(3),	20,	_INV(3),	_INV(3),	19,	_INV(3),\
	_INV(3),	18,	_INV(3),	_INV(3),	17,	_INV(3),	_INV(3),	16,\
	_INV(3),	_INV(3),	15,	_INV(3),	_INV(3),	14,	_INV(3),	_INV(3),\
	13,	_INV(3),	_INV(3),	12,	_INV(3),	_INV(3),	11,	_INV(3),\
	_INV(3),	10,	_INV(3),	_INV(3),	9,	_INV(3),	_INV(3),	8,\
	_INV(3),	_INV(3),	7,	_INV(3),	_INV(3),	6,	_INV(3),	_INV(3),\
	5,	_INV(3),	_INV(3),	4,	_INV(3),	_INV(3),	3,	_INV(3),\
	_INV(3),	2,	_INV(3),	_INV(3),	1,	_INV(3),	_INV(3),	0,)
#define _NARG_4(...) _ARG(__VA_ARGS__, \
	_INV(4),	_INV(4),	_INV(4),	15,	_INV(4),	_INV(4),	_INV(4),	14,\
	_INV(4),	_INV(4),	_INV(4),	13,	_INV(4),	_INV(4),	_INV(4),	12,\
	_INV(4),	_INV(4),	_INV(4),	11,	_INV(4),	_INV(4),	_INV(4),	10,\
	_INV(4),	_INV(4),	_INV(4),	9,	_INV(4),	_INV(4),	_INV(4),	8,\
	_INV(4),	_INV(4),	_INV(4),	7,	_INV(4),	_INV(4),	_INV(4),	6,\
	_INV(4),	_INV(4),	_INV(4),	5,	_INV(4),	_INV(4),	_INV(4),	4,\
	_INV(4),	_INV(4),	_INV(4),	3,	_INV(4),	_INV(4),	_INV(4),	2,\
	_INV(4),	_INV(4),	_INV(4),	1,	_INV(4),	_INV(4),	_INV(4),	0,)
#define _ASCENDING() \
	0,	1,	2,	3,	4,	5,	6,	7,\
	8,	9,	10,	11,	12,	13,	14,	15,\
	16,	17,	18,	19,	20,	21,	22,	23,\
	24,	25,	26,	27,	28,	29,	30,	31,\
	32,	33,	34,	35,	36,	37,	38,	39,\
	40,	41,	42,	43,	44,	45,	46,	47,\
	48,	49,	50,	51,	52,	53,	54,	55,\
	56,	57,	58,	59,	60,	61,	62,	63,	64
#define PASTE3(_1,	_2,	_3)	\
	_PASTE2(PASTE2(_1,	_2), _3)
#define PASTE4(_1,	_2,	_3,	_4)	\
	_PASTE2(PASTE3(_1,	_2,	_3), _4)
#define PASTE5(_1,	_2,	_3,	_4,	_5)	\
	_PASTE2(PASTE4(_1,	_2,	_3,	_4), _5)
#define PASTE6(_1,	_2,	_3,	_4,	_5,	_6)	\
	_PASTE2(PASTE5(_1,	_2,	_3,	_4,	_5), _6)
#define PASTE7(_1,	_2,	_3,	_4,	_5,	_6,	_7)	\
	_PASTE2(PASTE6(_1,	_2,	_3,	_4,	_5,	_6), _7)
#define PASTE8(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8)	\
	_PASTE2(PASTE7(_1,	_2,	_3,	_4,	_5,	_6,	_7), _8)
#define PASTE9(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9)	\
	_PASTE2(PASTE8(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8), _9)
#define PASTE10(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10)	\
	_PASTE2(PASTE9(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9), _10)
#define PASTE11(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11)	\
	_PASTE2(PASTE10(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10), _11)
#define PASTE12(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12)	\
	_PASTE2(PASTE11(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11), _12)
#define PASTE13(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13)	\
	_PASTE2(PASTE12(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12), _13)
#define PASTE14(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13,	_14)	\
	_PASTE2(PASTE13(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13), _14)
#define PASTE15(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13,	_14,	_15)	\
	_PASTE2(PASTE14(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13,	_14), _15)
#define PASTE16(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13,	_14,	_15,	_16)	\
	_PASTE2(PASTE15(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13,	_14,	_15), _16)
#define PASTE17(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13,	_14,	_15,	_16,	_17)	\
	_PASTE2(PASTE16(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13,	_14,	_15,	_16), _17)
#define PASTE18(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13,	_14,	_15,	_16,	_17,	_18)	\
	_PASTE2(PASTE17(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13,	_14,	_15,	_16,	_17), _18)
#define PASTE19(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13,	_14,	_15,	_16,	_17,	_18,	_19)	\
	_PASTE2(PASTE18(_1,	_2,	_3,	_4,	_5,	_6,	_7,	_8,	_9,	_10,	_11,	_12,	_13,	_14,	_15,	_16,	_17,	_18), _19)
#define _hex2dec_0x0 0
#define _hex2dec_0x1 1
#define _hex2dec_0x2 2
#define _hex2dec_0x3 3
#define _hex2dec_0x4 4
#define _hex2dec_0x5 5
#define _hex2dec_0x6 6
#define _hex2dec_0x7 7
#define _hex2dec_0x8 8
#define _hex2dec_0x9 9
#define _hex2dec_0xA 10
#define _hex2dec_0xB 11
#define _hex2dec_0xC 12
#define _hex2dec_0xD 13
#define _hex2dec_0xE 14
#define _hex2dec_0xF 15
#define _hex2dec_0x00 0
#define _hex2dec_0x01 1
#define _hex2dec_0x02 2
#define _hex2dec_0x03 3
#define _hex2dec_0x04 4
#define _hex2dec_0x05 5
#define _hex2dec_0x06 6
#define _hex2dec_0x07 7
#define _hex2dec_0x08 8
#define _hex2dec_0x09 9
#define _hex2dec_0x0A 10
#define _hex2dec_0x0B 11
#define _hex2dec_0x0C 12
#define _hex2dec_0x0D 13
#define _hex2dec_0x0E 14
#define _hex2dec_0x0F 15
#define _hex2dec_0x10 16
#define _hex2dec_0x11 17
#define _hex2dec_0x12 18
#define _hex2dec_0x13 19
#define _hex2dec_0x14 20
#define _hex2dec_0x15 21
#define _hex2dec_0x16 22
#define _hex2dec_0x17 23
#define _hex2dec_0x18 24
#define _hex2dec_0x19 25
#define _hex2dec_0x1A 26
#define _hex2dec_0x1B 27
#define _hex2dec_0x1C 28
#define _hex2dec_0x1D 29
#define _hex2dec_0x1E 30
#define _hex2dec_0x1F 31
#define _hex2dec_0x20 32
#define _hex2dec_0x21 33
#define _hex2dec_0x22 34
#define _hex2dec_0x23 35
#define _hex2dec_0x24 36
#define _hex2dec_0x25 37
#define _hex2dec_0x26 38
#define _hex2dec_0x27 39
#define _hex2dec_0x28 40
#define _hex2dec_0x29 41
#define _hex2dec_0x2A 42
#define _hex2dec_0x2B 43
#define _hex2dec_0x2C 44
#define _hex2dec_0x2D 45
#define _hex2dec_0x2E 46
#define _hex2dec_0x2F 47
#define _hex2dec_0x30 48
#define _hex2dec_0x31 49
#define _hex2dec_0x32 50
#define _hex2dec_0x33 51
#define _hex2dec_0x34 52
#define _hex2dec_0x35 53
#define _hex2dec_0x36 54
#define _hex2dec_0x37 55
#define _hex2dec_0x38 56
#define _hex2dec_0x39 57
#define _hex2dec_0x3A 58
#define _hex2dec_0x3B 59
#define _hex2dec_0x3C 60
#define _hex2dec_0x3D 61
#define _hex2dec_0x3E 62
#define _hex2dec_0x3F 63
#define _hex2dec_0x000 0
#define _hex2dec_0x001 1
#define _hex2dec_0x002 2
#define _hex2dec_0x003 3
#define _hex2dec_0x004 4
#define _hex2dec_0x005 5
#define _hex2dec_0x006 6
#define _hex2dec_0x007 7
#define _hex2dec_0x008 8
#define _hex2dec_0x009 9
#define _hex2dec_0x00A 10
#define _hex2dec_0x00B 11
#define _hex2dec_0x00C 12
#define _hex2dec_0x00D 13
#define _hex2dec_0x00E 14
#define _hex2dec_0x00F 15
#define _hex2dec_0x010 16
#define _hex2dec_0x011 17
#define _hex2dec_0x012 18
#define _hex2dec_0x013 19
#define _hex2dec_0x014 20
#define _hex2dec_0x015 21
#define _hex2dec_0x016 22
#define _hex2dec_0x017 23
#define _hex2dec_0x018 24
#define _hex2dec_0x019 25
#define _hex2dec_0x01A 26
#define _hex2dec_0x01B 27
#define _hex2dec_0x01C 28
#define _hex2dec_0x01D 29
#define _hex2dec_0x01E 30
#define _hex2dec_0x01F 31
#define _hex2dec_0x020 32
#define _hex2dec_0x021 33
#define _hex2dec_0x022 34
#define _hex2dec_0x023 35
#define _hex2dec_0x024 36
#define _hex2dec_0x025 37
#define _hex2dec_0x026 38
#define _hex2dec_0x027 39
#define _hex2dec_0x028 40
#define _hex2dec_0x029 41
#define _hex2dec_0x02A 42
#define _hex2dec_0x02B 43
#define _hex2dec_0x02C 44
#define _hex2dec_0x02D 45
#define _hex2dec_0x02E 46
#define _hex2dec_0x02F 47
#define _hex2dec_0x030 48
#define _hex2dec_0x031 49
#define _hex2dec_0x032 50
#define _hex2dec_0x033 51
#define _hex2dec_0x034 52
#define _hex2dec_0x035 53
#define _hex2dec_0x036 54
#define _hex2dec_0x037 55
#define _hex2dec_0x038 56
#define _hex2dec_0x039 57
#define _hex2dec_0x03A 58
#define _hex2dec_0x03B 59
#define _hex2dec_0x03C 60
#define _hex2dec_0x03D 61
#define _hex2dec_0x03E 62
#define _hex2dec_0x03F 63
#define _dec2hex_0 000
#define _dec2hex_1 001
#define _dec2hex_2 002
#define _dec2hex_3 003
#define _dec2hex_4 004
#define _dec2hex_5 005
#define _dec2hex_6 006
#define _dec2hex_7 007
#define _dec2hex_8 008
#define _dec2hex_9 009
#define _dec2hex_10 00A
#define _dec2hex_11 00B
#define _dec2hex_12 00C
#define _dec2hex_13 00D
#define _dec2hex_14 00E
#define _dec2hex_15 00F
#define _dec2hex_16 010
#define _dec2hex_17 011
#define _dec2hex_18 012
#define _dec2hex_19 013
#define _dec2hex_20 014
#define _dec2hex_21 015
#define _dec2hex_22 016
#define _dec2hex_23 017
#define _dec2hex_24 018
#define _dec2hex_25 019
#define _dec2hex_26 01A
#define _dec2hex_27 01B
#define _dec2hex_28 01C
#define _dec2hex_29 01D
#define _dec2hex_30 01E
#define _dec2hex_31 01F
#define _dec2hex_32 020
#define _dec2hex_33 021
#define _dec2hex_34 022
#define _dec2hex_35 023
#define _dec2hex_36 024
#define _dec2hex_37 025
#define _dec2hex_38 026
#define _dec2hex_39 027
#define _dec2hex_40 028
#define _dec2hex_41 029
#define _dec2hex_42 02A
#define _dec2hex_43 02B
#define _dec2hex_44 02C
#define _dec2hex_45 02D
#define _dec2hex_46 02E
#define _dec2hex_47 02F
#define _dec2hex_48 030
#define _dec2hex_49 031
#define _dec2hex_50 032
#define _dec2hex_51 033
#define _dec2hex_52 034
#define _dec2hex_53 035
#define _dec2hex_54 036
#define _dec2hex_55 037
#define _dec2hex_56 038
#define _dec2hex_57 039
#define _dec2hex_58 03A
#define _dec2hex_59 03B
#define _dec2hex_60 03C
#define _dec2hex_61 03D
#define _dec2hex_62 03E
#define _dec2hex_63 03F
#define _uni2dec_ 0
#define _dec2uni_0 
#define _predecessor_1 0
#define _itpredecessor_1(DEC) _predecessor(_itpredecessor_0(DEC))
#define _predecessor_minus_0 minus_1
#define _minus_minus_0 0
#define _IS_0_GE_0 ,
#define _dec_eval_0 0
#define _dec_eval_minus_0 0
#define _uni2dec_1 1
#define _dec2uni_1 1
#define _predecessor_2 1
#define _itpredecessor_2(DEC) _predecessor(_itpredecessor_1(DEC))
#define _predecessor_minus_1 minus_2
#define _minus_minus_1 1
#define _IS_1_GE_0 ,
#define _dec_eval_1 1
#define _dec_eval_minus_1 -1
#define _uni2dec_11 2
#define _dec2uni_2 11
#define _predecessor_3 2
#define _itpredecessor_3(DEC) _predecessor(_itpredecessor_2(DEC))
#define _predecessor_minus_2 minus_3
#define _minus_minus_2 2
#define _IS_2_GE_0 ,
#define _dec_eval_2 2
#define _dec_eval_minus_2 -2
#define _uni2dec_111 3
#define _dec2uni_3 111
#define _predecessor_4 3
#define _itpredecessor_4(DEC) _predecessor(_itpredecessor_3(DEC))
#define _predecessor_minus_3 minus_4
#define _minus_minus_3 3
#define _IS_3_GE_0 ,
#define _dec_eval_3 3
#define _dec_eval_minus_3 -3
#define _uni2dec_1111 4
#define _dec2uni_4 1111
#define _predecessor_5 4
#define _itpredecessor_5(DEC) _predecessor(_itpredecessor_4(DEC))
#define _predecessor_minus_4 minus_5
#define _minus_minus_4 4
#define _IS_4_GE_0 ,
#define _dec_eval_4 4
#define _dec_eval_minus_4 -4
#define _uni2dec_11111 5
#define _dec2uni_5 11111
#define _predecessor_6 5
#define _itpredecessor_6(DEC) _predecessor(_itpredecessor_5(DEC))
#define _predecessor_minus_5 minus_6
#define _minus_minus_5 5
#define _IS_5_GE_0 ,
#define _dec_eval_5 5
#define _dec_eval_minus_5 -5
#define _uni2dec_111111 6
#define _dec2uni_6 111111
#define _predecessor_7 6
#define _itpredecessor_7(DEC) _predecessor(_itpredecessor_6(DEC))
#define _predecessor_minus_6 minus_7
#define _minus_minus_6 6
#define _IS_6_GE_0 ,
#define _dec_eval_6 6
#define _dec_eval_minus_6 -6
#define _uni2dec_1111111 7
#define _dec2uni_7 1111111
#define _predecessor_8 7
#define _itpredecessor_8(DEC) _predecessor(_itpredecessor_7(DEC))
#define _predecessor_minus_7 minus_8
#define _minus_minus_7 7
#define _IS_7_GE_0 ,
#define _dec_eval_7 7
#define _dec_eval_minus_7 -7
#define _uni2dec_11111111 8
#define _dec2uni_8 11111111
#define _predecessor_9 8
#define _itpredecessor_9(DEC) _predecessor(_itpredecessor_8(DEC))
#define _predecessor_minus_8 minus_9
#define _minus_minus_8 8
#define _IS_8_GE_0 ,
#define _dec_eval_8 8
#define _dec_eval_minus_8 -8
#define _uni2dec_111111111 9
#define _dec2uni_9 111111111
#define _predecessor_10 9
#define _itpredecessor_10(DEC) _predecessor(_itpredecessor_9(DEC))
#define _predecessor_minus_9 minus_10
#define _minus_minus_9 9
#define _IS_9_GE_0 ,
#define _dec_eval_9 9
#define _dec_eval_minus_9 -9
#define _uni2dec_1111111111 10
#define _dec2uni_10 1111111111
#define _predecessor_11 10
#define _itpredecessor_11(DEC) _predecessor(_itpredecessor_10(DEC))
#define _predecessor_minus_10 minus_11
#define _minus_minus_10 10
#define _IS_10_GE_0 ,
#define _dec_eval_10 10
#define _dec_eval_minus_10 -10
#define _uni2dec_11111111111 11
#define _dec2uni_11 11111111111
#define _predecessor_12 11
#define _itpredecessor_12(DEC) _predecessor(_itpredecessor_11(DEC))
#define _predecessor_minus_11 minus_12
#define _minus_minus_11 11
#define _IS_11_GE_0 ,
#define _dec_eval_11 11
#define _dec_eval_minus_11 -11
#define _uni2dec_111111111111 12
#define _dec2uni_12 111111111111
#define _predecessor_13 12
#define _itpredecessor_13(DEC) _predecessor(_itpredecessor_12(DEC))
#define _predecessor_minus_12 minus_13
#define _minus_minus_12 12
#define _IS_12_GE_0 ,
#define _dec_eval_12 12
#define _dec_eval_minus_12 -12
#define _uni2dec_1111111111111 13
#define _dec2uni_13 1111111111111
#define _predecessor_14 13
#define _itpredecessor_14(DEC) _predecessor(_itpredecessor_13(DEC))
#define _predecessor_minus_13 minus_14
#define _minus_minus_13 13
#define _IS_13_GE_0 ,
#define _dec_eval_13 13
#define _dec_eval_minus_13 -13
#define _uni2dec_11111111111111 14
#define _dec2uni_14 11111111111111
#define _predecessor_15 14
#define _itpredecessor_15(DEC) _predecessor(_itpredecessor_14(DEC))
#define _predecessor_minus_14 minus_15
#define _minus_minus_14 14
#define _IS_14_GE_0 ,
#define _dec_eval_14 14
#define _dec_eval_minus_14 -14
#define _uni2dec_111111111111111 15
#define _dec2uni_15 111111111111111
#define _predecessor_16 15
#define _itpredecessor_16(DEC) _predecessor(_itpredecessor_15(DEC))
#define _predecessor_minus_15 minus_16
#define _minus_minus_15 15
#define _IS_15_GE_0 ,
#define _dec_eval_15 15
#define _dec_eval_minus_15 -15
#define _uni2dec_1111111111111111 16
#define _dec2uni_16 1111111111111111
#define _predecessor_17 16
#define _itpredecessor_17(DEC) _predecessor(_itpredecessor_16(DEC))
#define _predecessor_minus_16 minus_17
#define _minus_minus_16 16
#define _IS_16_GE_0 ,
#define _dec_eval_16 16
#define _dec_eval_minus_16 -16
#define _uni2dec_11111111111111111 17
#define _dec2uni_17 11111111111111111
#define _predecessor_18 17
#define _itpredecessor_18(DEC) _predecessor(_itpredecessor_17(DEC))
#define _predecessor_minus_17 minus_18
#define _minus_minus_17 17
#define _IS_17_GE_0 ,
#define _dec_eval_17 17
#define _dec_eval_minus_17 -17
#define _uni2dec_111111111111111111 18
#define _dec2uni_18 111111111111111111
#define _predecessor_19 18
#define _itpredecessor_19(DEC) _predecessor(_itpredecessor_18(DEC))
#define _predecessor_minus_18 minus_19
#define _minus_minus_18 18
#define _IS_18_GE_0 ,
#define _dec_eval_18 18
#define _dec_eval_minus_18 -18
#define _uni2dec_1111111111111111111 19
#define _dec2uni_19 1111111111111111111
#define _predecessor_20 19
#define _itpredecessor_20(DEC) _predecessor(_itpredecessor_19(DEC))
#define _predecessor_minus_19 minus_20
#define _minus_minus_19 19
#define _IS_19_GE_0 ,
#define _dec_eval_19 19
#define _dec_eval_minus_19 -19
#define _uni2dec_11111111111111111111 20
#define _dec2uni_20 11111111111111111111
#define _predecessor_21 20
#define _itpredecessor_21(DEC) _predecessor(_itpredecessor_20(DEC))
#define _predecessor_minus_20 minus_21
#define _minus_minus_20 20
#define _IS_20_GE_0 ,
#define _dec_eval_20 20
#define _dec_eval_minus_20 -20
#define _uni2dec_111111111111111111111 21
#define _dec2uni_21 111111111111111111111
#define _predecessor_22 21
#define _itpredecessor_22(DEC) _predecessor(_itpredecessor_21(DEC))
#define _predecessor_minus_21 minus_22
#define _minus_minus_21 21
#define _IS_21_GE_0 ,
#define _dec_eval_21 21
#define _dec_eval_minus_21 -21
#define _uni2dec_1111111111111111111111 22
#define _dec2uni_22 1111111111111111111111
#define _predecessor_23 22
#define _itpredecessor_23(DEC) _predecessor(_itpredecessor_22(DEC))
#define _predecessor_minus_22 minus_23
#define _minus_minus_22 22
#define _IS_22_GE_0 ,
#define _dec_eval_22 22
#define _dec_eval_minus_22 -22
#define _uni2dec_11111111111111111111111 23
#define _dec2uni_23 11111111111111111111111
#define _predecessor_24 23
#define _itpredecessor_24(DEC) _predecessor(_itpredecessor_23(DEC))
#define _predecessor_minus_23 minus_24
#define _minus_minus_23 23
#define _IS_23_GE_0 ,
#define _dec_eval_23 23
#define _dec_eval_minus_23 -23
#define _uni2dec_111111111111111111111111 24
#define _dec2uni_24 111111111111111111111111
#define _predecessor_25 24
#define _itpredecessor_25(DEC) _predecessor(_itpredecessor_24(DEC))
#define _predecessor_minus_24 minus_25
#define _minus_minus_24 24
#define _IS_24_GE_0 ,
#define _dec_eval_24 24
#define _dec_eval_minus_24 -24
#define _uni2dec_1111111111111111111111111 25
#define _dec2uni_25 1111111111111111111111111
#define _predecessor_26 25
#define _itpredecessor_26(DEC) _predecessor(_itpredecessor_25(DEC))
#define _predecessor_minus_25 minus_26
#define _minus_minus_25 25
#define _IS_25_GE_0 ,
#define _dec_eval_25 25
#define _dec_eval_minus_25 -25
#define _uni2dec_11111111111111111111111111 26
#define _dec2uni_26 11111111111111111111111111
#define _predecessor_27 26
#define _itpredecessor_27(DEC) _predecessor(_itpredecessor_26(DEC))
#define _predecessor_minus_26 minus_27
#define _minus_minus_26 26
#define _IS_26_GE_0 ,
#define _dec_eval_26 26
#define _dec_eval_minus_26 -26
#define _uni2dec_111111111111111111111111111 27
#define _dec2uni_27 111111111111111111111111111
#define _predecessor_28 27
#define _itpredecessor_28(DEC) _predecessor(_itpredecessor_27(DEC))
#define _predecessor_minus_27 minus_28
#define _minus_minus_27 27
#define _IS_27_GE_0 ,
#define _dec_eval_27 27
#define _dec_eval_minus_27 -27
#define _uni2dec_1111111111111111111111111111 28
#define _dec2uni_28 1111111111111111111111111111
#define _predecessor_29 28
#define _itpredecessor_29(DEC) _predecessor(_itpredecessor_28(DEC))
#define _predecessor_minus_28 minus_29
#define _minus_minus_28 28
#define _IS_28_GE_0 ,
#define _dec_eval_28 28
#define _dec_eval_minus_28 -28
#define _uni2dec_11111111111111111111111111111 29
#define _dec2uni_29 11111111111111111111111111111
#define _predecessor_30 29
#define _itpredecessor_30(DEC) _predecessor(_itpredecessor_29(DEC))
#define _predecessor_minus_29 minus_30
#define _minus_minus_29 29
#define _IS_29_GE_0 ,
#define _dec_eval_29 29
#define _dec_eval_minus_29 -29
#define _uni2dec_111111111111111111111111111111 30
#define _dec2uni_30 111111111111111111111111111111
#define _predecessor_31 30
#define _itpredecessor_31(DEC) _predecessor(_itpredecessor_30(DEC))
#define _predecessor_minus_30 minus_31
#define _minus_minus_30 30
#define _IS_30_GE_0 ,
#define _dec_eval_30 30
#define _dec_eval_minus_30 -30
#define _uni2dec_1111111111111111111111111111111 31
#define _dec2uni_31 1111111111111111111111111111111
#define _predecessor_32 31
#define _itpredecessor_32(DEC) _predecessor(_itpredecessor_31(DEC))
#define _predecessor_minus_31 minus_32
#define _minus_minus_31 31
#define _IS_31_GE_0 ,
#define _dec_eval_31 31
#define _dec_eval_minus_31 -31
#define _uni2dec_11111111111111111111111111111111 32
#define _dec2uni_32 11111111111111111111111111111111
#define _predecessor_33 32
#define _itpredecessor_33(DEC) _predecessor(_itpredecessor_32(DEC))
#define _predecessor_minus_32 minus_33
#define _minus_minus_32 32
#define _IS_32_GE_0 ,
#define _dec_eval_32 32
#define _dec_eval_minus_32 -32
#define _uni2dec_111111111111111111111111111111111 33
#define _dec2uni_33 111111111111111111111111111111111
#define _predecessor_34 33
#define _itpredecessor_34(DEC) _predecessor(_itpredecessor_33(DEC))
#define _predecessor_minus_33 minus_34
#define _minus_minus_33 33
#define _IS_33_GE_0 ,
#define _dec_eval_33 33
#define _dec_eval_minus_33 -33
#define _uni2dec_1111111111111111111111111111111111 34
#define _dec2uni_34 1111111111111111111111111111111111
#define _predecessor_35 34
#define _itpredecessor_35(DEC) _predecessor(_itpredecessor_34(DEC))
#define _predecessor_minus_34 minus_35
#define _minus_minus_34 34
#define _IS_34_GE_0 ,
#define _dec_eval_34 34
#define _dec_eval_minus_34 -34
#define _uni2dec_11111111111111111111111111111111111 35
#define _dec2uni_35 11111111111111111111111111111111111
#define _predecessor_36 35
#define _itpredecessor_36(DEC) _predecessor(_itpredecessor_35(DEC))
#define _predecessor_minus_35 minus_36
#define _minus_minus_35 35
#define _IS_35_GE_0 ,
#define _dec_eval_35 35
#define _dec_eval_minus_35 -35
#define _uni2dec_111111111111111111111111111111111111 36
#define _dec2uni_36 111111111111111111111111111111111111
#define _predecessor_37 36
#define _itpredecessor_37(DEC) _predecessor(_itpredecessor_36(DEC))
#define _predecessor_minus_36 minus_37
#define _minus_minus_36 36
#define _IS_36_GE_0 ,
#define _dec_eval_36 36
#define _dec_eval_minus_36 -36
#define _uni2dec_1111111111111111111111111111111111111 37
#define _dec2uni_37 1111111111111111111111111111111111111
#define _predecessor_38 37
#define _itpredecessor_38(DEC) _predecessor(_itpredecessor_37(DEC))
#define _predecessor_minus_37 minus_38
#define _minus_minus_37 37
#define _IS_37_GE_0 ,
#define _dec_eval_37 37
#define _dec_eval_minus_37 -37
#define _uni2dec_11111111111111111111111111111111111111 38
#define _dec2uni_38 11111111111111111111111111111111111111
#define _predecessor_39 38
#define _itpredecessor_39(DEC) _predecessor(_itpredecessor_38(DEC))
#define _predecessor_minus_38 minus_39
#define _minus_minus_38 38
#define _IS_38_GE_0 ,
#define _dec_eval_38 38
#define _dec_eval_minus_38 -38
#define _uni2dec_111111111111111111111111111111111111111 39
#define _dec2uni_39 111111111111111111111111111111111111111
#define _predecessor_40 39
#define _itpredecessor_40(DEC) _predecessor(_itpredecessor_39(DEC))
#define _predecessor_minus_39 minus_40
#define _minus_minus_39 39
#define _IS_39_GE_0 ,
#define _dec_eval_39 39
#define _dec_eval_minus_39 -39
#define _uni2dec_1111111111111111111111111111111111111111 40
#define _dec2uni_40 1111111111111111111111111111111111111111
#define _predecessor_41 40
#define _itpredecessor_41(DEC) _predecessor(_itpredecessor_40(DEC))
#define _predecessor_minus_40 minus_41
#define _minus_minus_40 40
#define _IS_40_GE_0 ,
#define _dec_eval_40 40
#define _dec_eval_minus_40 -40
#define _uni2dec_11111111111111111111111111111111111111111 41
#define _dec2uni_41 11111111111111111111111111111111111111111
#define _predecessor_42 41
#define _itpredecessor_42(DEC) _predecessor(_itpredecessor_41(DEC))
#define _predecessor_minus_41 minus_42
#define _minus_minus_41 41
#define _IS_41_GE_0 ,
#define _dec_eval_41 41
#define _dec_eval_minus_41 -41
#define _uni2dec_111111111111111111111111111111111111111111 42
#define _dec2uni_42 111111111111111111111111111111111111111111
#define _predecessor_43 42
#define _itpredecessor_43(DEC) _predecessor(_itpredecessor_42(DEC))
#define _predecessor_minus_42 minus_43
#define _minus_minus_42 42
#define _IS_42_GE_0 ,
#define _dec_eval_42 42
#define _dec_eval_minus_42 -42
#define _uni2dec_1111111111111111111111111111111111111111111 43
#define _dec2uni_43 1111111111111111111111111111111111111111111
#define _predecessor_44 43
#define _itpredecessor_44(DEC) _predecessor(_itpredecessor_43(DEC))
#define _predecessor_minus_43 minus_44
#define _minus_minus_43 43
#define _IS_43_GE_0 ,
#define _dec_eval_43 43
#define _dec_eval_minus_43 -43
#define _uni2dec_11111111111111111111111111111111111111111111 44
#define _dec2uni_44 11111111111111111111111111111111111111111111
#define _predecessor_45 44
#define _itpredecessor_45(DEC) _predecessor(_itpredecessor_44(DEC))
#define _predecessor_minus_44 minus_45
#define _minus_minus_44 44
#define _IS_44_GE_0 ,
#define _dec_eval_44 44
#define _dec_eval_minus_44 -44
#define _uni2dec_111111111111111111111111111111111111111111111 45
#define _dec2uni_45 111111111111111111111111111111111111111111111
#define _predecessor_46 45
#define _itpredecessor_46(DEC) _predecessor(_itpredecessor_45(DEC))
#define _predecessor_minus_45 minus_46
#define _minus_minus_45 45
#define _IS_45_GE_0 ,
#define _dec_eval_45 45
#define _dec_eval_minus_45 -45
#define _uni2dec_1111111111111111111111111111111111111111111111 46
#define _dec2uni_46 1111111111111111111111111111111111111111111111
#define _predecessor_47 46
#define _itpredecessor_47(DEC) _predecessor(_itpredecessor_46(DEC))
#define _predecessor_minus_46 minus_47
#define _minus_minus_46 46
#define _IS_46_GE_0 ,
#define _dec_eval_46 46
#define _dec_eval_minus_46 -46
#define _uni2dec_11111111111111111111111111111111111111111111111 47
#define _dec2uni_47 11111111111111111111111111111111111111111111111
#define _predecessor_48 47
#define _itpredecessor_48(DEC) _predecessor(_itpredecessor_47(DEC))
#define _predecessor_minus_47 minus_48
#define _minus_minus_47 47
#define _IS_47_GE_0 ,
#define _dec_eval_47 47
#define _dec_eval_minus_47 -47
#define _uni2dec_111111111111111111111111111111111111111111111111 48
#define _dec2uni_48 111111111111111111111111111111111111111111111111
#define _predecessor_49 48
#define _itpredecessor_49(DEC) _predecessor(_itpredecessor_48(DEC))
#define _predecessor_minus_48 minus_49
#define _minus_minus_48 48
#define _IS_48_GE_0 ,
#define _dec_eval_48 48
#define _dec_eval_minus_48 -48
#define _uni2dec_1111111111111111111111111111111111111111111111111 49
#define _dec2uni_49 1111111111111111111111111111111111111111111111111
#define _predecessor_50 49
#define _itpredecessor_50(DEC) _predecessor(_itpredecessor_49(DEC))
#define _predecessor_minus_49 minus_50
#define _minus_minus_49 49
#define _IS_49_GE_0 ,
#define _dec_eval_49 49
#define _dec_eval_minus_49 -49
#define _uni2dec_11111111111111111111111111111111111111111111111111 50
#define _dec2uni_50 11111111111111111111111111111111111111111111111111
#define _predecessor_51 50
#define _itpredecessor_51(DEC) _predecessor(_itpredecessor_50(DEC))
#define _predecessor_minus_50 minus_51
#define _minus_minus_50 50
#define _IS_50_GE_0 ,
#define _dec_eval_50 50
#define _dec_eval_minus_50 -50
#define _uni2dec_111111111111111111111111111111111111111111111111111 51
#define _dec2uni_51 111111111111111111111111111111111111111111111111111
#define _predecessor_52 51
#define _itpredecessor_52(DEC) _predecessor(_itpredecessor_51(DEC))
#define _predecessor_minus_51 minus_52
#define _minus_minus_51 51
#define _IS_51_GE_0 ,
#define _dec_eval_51 51
#define _dec_eval_minus_51 -51
#define _uni2dec_1111111111111111111111111111111111111111111111111111 52
#define _dec2uni_52 1111111111111111111111111111111111111111111111111111
#define _predecessor_53 52
#define _itpredecessor_53(DEC) _predecessor(_itpredecessor_52(DEC))
#define _predecessor_minus_52 minus_53
#define _minus_minus_52 52
#define _IS_52_GE_0 ,
#define _dec_eval_52 52
#define _dec_eval_minus_52 -52
#define _uni2dec_11111111111111111111111111111111111111111111111111111 53
#define _dec2uni_53 11111111111111111111111111111111111111111111111111111
#define _predecessor_54 53
#define _itpredecessor_54(DEC) _predecessor(_itpredecessor_53(DEC))
#define _predecessor_minus_53 minus_54
#define _minus_minus_53 53
#define _IS_53_GE_0 ,
#define _dec_eval_53 53
#define _dec_eval_minus_53 -53
#define _uni2dec_111111111111111111111111111111111111111111111111111111 54
#define _dec2uni_54 111111111111111111111111111111111111111111111111111111
#define _predecessor_55 54
#define _itpredecessor_55(DEC) _predecessor(_itpredecessor_54(DEC))
#define _predecessor_minus_54 minus_55
#define _minus_minus_54 54
#define _IS_54_GE_0 ,
#define _dec_eval_54 54
#define _dec_eval_minus_54 -54
#define _uni2dec_1111111111111111111111111111111111111111111111111111111 55
#define _dec2uni_55 1111111111111111111111111111111111111111111111111111111
#define _predecessor_56 55
#define _itpredecessor_56(DEC) _predecessor(_itpredecessor_55(DEC))
#define _predecessor_minus_55 minus_56
#define _minus_minus_55 55
#define _IS_55_GE_0 ,
#define _dec_eval_55 55
#define _dec_eval_minus_55 -55
#define _uni2dec_11111111111111111111111111111111111111111111111111111111 56
#define _dec2uni_56 11111111111111111111111111111111111111111111111111111111
#define _predecessor_57 56
#define _itpredecessor_57(DEC) _predecessor(_itpredecessor_56(DEC))
#define _predecessor_minus_56 minus_57
#define _minus_minus_56 56
#define _IS_56_GE_0 ,
#define _dec_eval_56 56
#define _dec_eval_minus_56 -56
#define _uni2dec_111111111111111111111111111111111111111111111111111111111 57
#define _dec2uni_57 111111111111111111111111111111111111111111111111111111111
#define _predecessor_58 57
#define _itpredecessor_58(DEC) _predecessor(_itpredecessor_57(DEC))
#define _predecessor_minus_57 minus_58
#define _minus_minus_57 57
#define _IS_57_GE_0 ,
#define _dec_eval_57 57
#define _dec_eval_minus_57 -57
#define _uni2dec_1111111111111111111111111111111111111111111111111111111111 58
#define _dec2uni_58 1111111111111111111111111111111111111111111111111111111111
#define _predecessor_59 58
#define _itpredecessor_59(DEC) _predecessor(_itpredecessor_58(DEC))
#define _predecessor_minus_58 minus_59
#define _minus_minus_58 58
#define _IS_58_GE_0 ,
#define _dec_eval_58 58
#define _dec_eval_minus_58 -58
#define _uni2dec_11111111111111111111111111111111111111111111111111111111111 59
#define _dec2uni_59 11111111111111111111111111111111111111111111111111111111111
#define _predecessor_60 59
#define _itpredecessor_60(DEC) _predecessor(_itpredecessor_59(DEC))
#define _predecessor_minus_59 minus_60
#define _minus_minus_59 59
#define _IS_59_GE_0 ,
#define _dec_eval_59 59
#define _dec_eval_minus_59 -59
#define _uni2dec_111111111111111111111111111111111111111111111111111111111111 60
#define _dec2uni_60 111111111111111111111111111111111111111111111111111111111111
#define _predecessor_61 60
#define _itpredecessor_61(DEC) _predecessor(_itpredecessor_60(DEC))
#define _predecessor_minus_60 minus_61
#define _minus_minus_60 60
#define _IS_60_GE_0 ,
#define _dec_eval_60 60
#define _dec_eval_minus_60 -60
#define _uni2dec_1111111111111111111111111111111111111111111111111111111111111 61
#define _dec2uni_61 1111111111111111111111111111111111111111111111111111111111111
#define _predecessor_62 61
#define _itpredecessor_62(DEC) _predecessor(_itpredecessor_61(DEC))
#define _predecessor_minus_61 minus_62
#define _minus_minus_61 61
#define _IS_61_GE_0 ,
#define _dec_eval_61 61
#define _dec_eval_minus_61 -61
#define _uni2dec_11111111111111111111111111111111111111111111111111111111111111 62
#define _dec2uni_62 11111111111111111111111111111111111111111111111111111111111111
#define _predecessor_63 62
#define _itpredecessor_63(DEC) _predecessor(_itpredecessor_62(DEC))
#define _predecessor_minus_62 minus_63
#define _minus_minus_62 62
#define _IS_62_GE_0 ,
#define _dec_eval_62 62
#define _dec_eval_minus_62 -62
#define _uni2dec_111111111111111111111111111111111111111111111111111111111111111 63
#define _dec2uni_63 111111111111111111111111111111111111111111111111111111111111111
#define _predecessor_64 63
#define _itpredecessor_64(DEC) _predecessor(_itpredecessor_63(DEC))
#define _predecessor_minus_63 minus_64
#define _minus_minus_63 63
#define _IS_63_GE_0 ,
#define _dec_eval_63 63
#define _dec_eval_minus_63 -63
#define __wda_1(NAME, N, ...) _wda_0(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_1(NAME, ...) __wda_1(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_1(NAME, ...) __VA_ARGS__
#define __wda_2(NAME, N, ...) _wda_1(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_2(NAME, ...) __wda_2(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_2(NAME, ...) __VA_ARGS__
#define __wda_3(NAME, N, ...) _wda_2(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_3(NAME, ...) __wda_3(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_3(NAME, ...) __VA_ARGS__
#define __wda_4(NAME, N, ...) _wda_3(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_4(NAME, ...) __wda_4(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_4(NAME, ...) __VA_ARGS__
#define __wda_5(NAME, N, ...) _wda_4(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_5(NAME, ...) __wda_5(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_5(NAME, ...) __VA_ARGS__
#define __wda_6(NAME, N, ...) _wda_5(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_6(NAME, ...) __wda_6(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_6(NAME, ...) __VA_ARGS__
#define __wda_7(NAME, N, ...) _wda_6(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_7(NAME, ...) __wda_7(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_7(NAME, ...) __VA_ARGS__
#define __wda_8(NAME, N, ...) _wda_7(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_8(NAME, ...) __wda_8(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_8(NAME, ...) __VA_ARGS__
#define __wda_9(NAME, N, ...) _wda_8(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_9(NAME, ...) __wda_9(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_9(NAME, ...) __VA_ARGS__
#define __wda_10(NAME, N, ...) _wda_9(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_10(NAME, ...) __wda_10(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_10(NAME, ...) __VA_ARGS__
#define __wda_11(NAME, N, ...) _wda_10(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_11(NAME, ...) __wda_11(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_11(NAME, ...) __VA_ARGS__
#define __wda_12(NAME, N, ...) _wda_11(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_12(NAME, ...) __wda_12(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_12(NAME, ...) __VA_ARGS__
#define __wda_13(NAME, N, ...) _wda_12(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_13(NAME, ...) __wda_13(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_13(NAME, ...) __VA_ARGS__
#define __wda_14(NAME, N, ...) _wda_13(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_14(NAME, ...) __wda_14(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_14(NAME, ...) __VA_ARGS__
#define __wda_15(NAME, N, ...) _wda_14(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_15(NAME, ...) __wda_15(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_15(NAME, ...) __VA_ARGS__
#define __wda_16(NAME, N, ...) _wda_15(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_16(NAME, ...) __wda_16(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_16(NAME, ...) __VA_ARGS__
#define __wda_17(NAME, N, ...) _wda_16(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_17(NAME, ...) __wda_17(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_17(NAME, ...) __VA_ARGS__
#define __wda_18(NAME, N, ...) _wda_17(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_18(NAME, ...) __wda_18(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_18(NAME, ...) __VA_ARGS__
#define __wda_19(NAME, N, ...) _wda_18(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_19(NAME, ...) __wda_19(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_19(NAME, ...) __VA_ARGS__
#define __wda_20(NAME, N, ...) _wda_19(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_20(NAME, ...) __wda_20(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_20(NAME, ...) __VA_ARGS__
#define __wda_21(NAME, N, ...) _wda_20(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_21(NAME, ...) __wda_21(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_21(NAME, ...) __VA_ARGS__
#define __wda_22(NAME, N, ...) _wda_21(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_22(NAME, ...) __wda_22(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_22(NAME, ...) __VA_ARGS__
#define __wda_23(NAME, N, ...) _wda_22(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_23(NAME, ...) __wda_23(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_23(NAME, ...) __VA_ARGS__
#define __wda_24(NAME, N, ...) _wda_23(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_24(NAME, ...) __wda_24(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_24(NAME, ...) __VA_ARGS__
#define __wda_25(NAME, N, ...) _wda_24(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_25(NAME, ...) __wda_25(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_25(NAME, ...) __VA_ARGS__
#define __wda_26(NAME, N, ...) _wda_25(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_26(NAME, ...) __wda_26(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_26(NAME, ...) __VA_ARGS__
#define __wda_27(NAME, N, ...) _wda_26(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_27(NAME, ...) __wda_27(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_27(NAME, ...) __VA_ARGS__
#define __wda_28(NAME, N, ...) _wda_27(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_28(NAME, ...) __wda_28(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_28(NAME, ...) __VA_ARGS__
#define __wda_29(NAME, N, ...) _wda_28(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_29(NAME, ...) __wda_29(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_29(NAME, ...) __VA_ARGS__
#define __wda_30(NAME, N, ...) _wda_29(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_30(NAME, ...) __wda_30(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_30(NAME, ...) __VA_ARGS__
#define __wda_31(NAME, N, ...) _wda_30(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_31(NAME, ...) __wda_31(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_31(NAME, ...) __VA_ARGS__
#define __wda_32(NAME, N, ...) _wda_31(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_32(NAME, ...) __wda_32(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_32(NAME, ...) __VA_ARGS__
#define __wda_33(NAME, N, ...) _wda_32(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_33(NAME, ...) __wda_33(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_33(NAME, ...) __VA_ARGS__
#define __wda_34(NAME, N, ...) _wda_33(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_34(NAME, ...) __wda_34(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_34(NAME, ...) __VA_ARGS__
#define __wda_35(NAME, N, ...) _wda_34(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_35(NAME, ...) __wda_35(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_35(NAME, ...) __VA_ARGS__
#define __wda_36(NAME, N, ...) _wda_35(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_36(NAME, ...) __wda_36(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_36(NAME, ...) __VA_ARGS__
#define __wda_37(NAME, N, ...) _wda_36(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_37(NAME, ...) __wda_37(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_37(NAME, ...) __VA_ARGS__
#define __wda_38(NAME, N, ...) _wda_37(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_38(NAME, ...) __wda_38(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_38(NAME, ...) __VA_ARGS__
#define __wda_39(NAME, N, ...) _wda_38(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_39(NAME, ...) __wda_39(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_39(NAME, ...) __VA_ARGS__
#define __wda_40(NAME, N, ...) _wda_39(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_40(NAME, ...) __wda_40(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_40(NAME, ...) __VA_ARGS__
#define __wda_41(NAME, N, ...) _wda_40(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_41(NAME, ...) __wda_41(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_41(NAME, ...) __VA_ARGS__
#define __wda_42(NAME, N, ...) _wda_41(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_42(NAME, ...) __wda_42(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_42(NAME, ...) __VA_ARGS__
#define __wda_43(NAME, N, ...) _wda_42(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_43(NAME, ...) __wda_43(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_43(NAME, ...) __VA_ARGS__
#define __wda_44(NAME, N, ...) _wda_43(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_44(NAME, ...) __wda_44(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_44(NAME, ...) __VA_ARGS__
#define __wda_45(NAME, N, ...) _wda_44(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_45(NAME, ...) __wda_45(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_45(NAME, ...) __VA_ARGS__
#define __wda_46(NAME, N, ...) _wda_45(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_46(NAME, ...) __wda_46(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_46(NAME, ...) __VA_ARGS__
#define __wda_47(NAME, N, ...) _wda_46(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_47(NAME, ...) __wda_47(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_47(NAME, ...) __VA_ARGS__
#define __wda_48(NAME, N, ...) _wda_47(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_48(NAME, ...) __wda_48(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_48(NAME, ...) __VA_ARGS__
#define __wda_49(NAME, N, ...) _wda_48(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_49(NAME, ...) __wda_49(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_49(NAME, ...) __VA_ARGS__
#define __wda_50(NAME, N, ...) _wda_49(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_50(NAME, ...) __wda_50(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_50(NAME, ...) __VA_ARGS__
#define __wda_51(NAME, N, ...) _wda_50(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_51(NAME, ...) __wda_51(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_51(NAME, ...) __VA_ARGS__
#define __wda_52(NAME, N, ...) _wda_51(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_52(NAME, ...) __wda_52(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_52(NAME, ...) __VA_ARGS__
#define __wda_53(NAME, N, ...) _wda_52(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_53(NAME, ...) __wda_53(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_53(NAME, ...) __VA_ARGS__
#define __wda_54(NAME, N, ...) _wda_53(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_54(NAME, ...) __wda_54(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_54(NAME, ...) __VA_ARGS__
#define __wda_55(NAME, N, ...) _wda_54(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_55(NAME, ...) __wda_55(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_55(NAME, ...) __VA_ARGS__
#define __wda_56(NAME, N, ...) _wda_55(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_56(NAME, ...) __wda_56(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_56(NAME, ...) __VA_ARGS__
#define __wda_57(NAME, N, ...) _wda_56(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_57(NAME, ...) __wda_57(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_57(NAME, ...) __VA_ARGS__
#define __wda_58(NAME, N, ...) _wda_57(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_58(NAME, ...) __wda_58(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_58(NAME, ...) __VA_ARGS__
#define __wda_59(NAME, N, ...) _wda_58(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_59(NAME, ...) __wda_59(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_59(NAME, ...) __VA_ARGS__
#define __wda_60(NAME, N, ...) _wda_59(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_60(NAME, ...) __wda_60(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_60(NAME, ...) __VA_ARGS__
#define __wda_61(NAME, N, ...) _wda_60(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_61(NAME, ...) __wda_61(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_61(NAME, ...) __VA_ARGS__
#define __wda_62(NAME, N, ...) _wda_61(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_62(NAME, ...) __wda_62(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_62(NAME, ...) __VA_ARGS__
#define __wda_63(NAME, N, ...) _wda_62(NAME, __VA_ARGS__, PASTE3(NAME, _defarg_, N)())
#define _wda_63(NAME, ...) __wda_63(NAME, _NARG(__VA_ARGS__), __VA_ARGS__)
#define _wda_minus_63(NAME, ...) __VA_ARGS__
#define __DOIT2(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT2(NAME, N, OP, FUNC, A, ...) __DOIT2(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT3(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT3(NAME, N, OP, FUNC, A, ...) __DOIT3(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT4(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT4(NAME, N, OP, FUNC, A, ...) __DOIT4(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT5(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT5(NAME, N, OP, FUNC, A, ...) __DOIT5(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT6(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT6(NAME, N, OP, FUNC, A, ...) __DOIT6(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT7(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT7(NAME, N, OP, FUNC, A, ...) __DOIT7(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT8(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT8(NAME, N, OP, FUNC, A, ...) __DOIT8(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT9(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT9(NAME, N, OP, FUNC, A, ...) __DOIT9(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT10(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT10(NAME, N, OP, FUNC, A, ...) __DOIT10(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT11(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT11(NAME, N, OP, FUNC, A, ...) __DOIT11(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT12(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT12(NAME, N, OP, FUNC, A, ...) __DOIT12(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT13(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT13(NAME, N, OP, FUNC, A, ...) __DOIT13(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT14(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT14(NAME, N, OP, FUNC, A, ...) __DOIT14(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT15(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT15(NAME, N, OP, FUNC, A, ...) __DOIT15(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT16(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT16(NAME, N, OP, FUNC, A, ...) __DOIT16(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT17(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT17(NAME, N, OP, FUNC, A, ...) __DOIT17(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT18(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT18(NAME, N, OP, FUNC, A, ...) __DOIT18(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT19(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT19(NAME, N, OP, FUNC, A, ...) __DOIT19(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT20(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT20(NAME, N, OP, FUNC, A, ...) __DOIT20(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT21(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT21(NAME, N, OP, FUNC, A, ...) __DOIT21(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT22(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT22(NAME, N, OP, FUNC, A, ...) __DOIT22(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT23(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT23(NAME, N, OP, FUNC, A, ...) __DOIT23(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT24(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT24(NAME, N, OP, FUNC, A, ...) __DOIT24(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT25(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT25(NAME, N, OP, FUNC, A, ...) __DOIT25(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT26(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT26(NAME, N, OP, FUNC, A, ...) __DOIT26(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT27(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT27(NAME, N, OP, FUNC, A, ...) __DOIT27(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT28(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT28(NAME, N, OP, FUNC, A, ...) __DOIT28(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT29(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT29(NAME, N, OP, FUNC, A, ...) __DOIT29(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT30(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT30(NAME, N, OP, FUNC, A, ...) __DOIT30(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT31(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT31(NAME, N, OP, FUNC, A, ...) __DOIT31(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT32(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT32(NAME, N, OP, FUNC, A, ...) __DOIT32(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT33(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT33(NAME, N, OP, FUNC, A, ...) __DOIT33(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT34(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT34(NAME, N, OP, FUNC, A, ...) __DOIT34(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT35(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT35(NAME, N, OP, FUNC, A, ...) __DOIT35(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT36(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT36(NAME, N, OP, FUNC, A, ...) __DOIT36(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT37(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT37(NAME, N, OP, FUNC, A, ...) __DOIT37(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT38(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT38(NAME, N, OP, FUNC, A, ...) __DOIT38(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT39(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT39(NAME, N, OP, FUNC, A, ...) __DOIT39(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT40(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT40(NAME, N, OP, FUNC, A, ...) __DOIT40(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT41(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT41(NAME, N, OP, FUNC, A, ...) __DOIT41(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT42(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT42(NAME, N, OP, FUNC, A, ...) __DOIT42(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT43(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT43(NAME, N, OP, FUNC, A, ...) __DOIT43(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT44(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT44(NAME, N, OP, FUNC, A, ...) __DOIT44(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT45(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT45(NAME, N, OP, FUNC, A, ...) __DOIT45(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT46(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT46(NAME, N, OP, FUNC, A, ...) __DOIT46(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT47(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT47(NAME, N, OP, FUNC, A, ...) __DOIT47(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT48(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT48(NAME, N, OP, FUNC, A, ...) __DOIT48(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT49(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT49(NAME, N, OP, FUNC, A, ...) __DOIT49(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT50(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT50(NAME, N, OP, FUNC, A, ...) __DOIT50(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT51(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT51(NAME, N, OP, FUNC, A, ...) __DOIT51(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT52(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT52(NAME, N, OP, FUNC, A, ...) __DOIT52(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT53(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT53(NAME, N, OP, FUNC, A, ...) __DOIT53(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT54(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT54(NAME, N, OP, FUNC, A, ...) __DOIT54(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT55(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT55(NAME, N, OP, FUNC, A, ...) __DOIT55(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT56(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT56(NAME, N, OP, FUNC, A, ...) __DOIT56(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT57(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT57(NAME, N, OP, FUNC, A, ...) __DOIT57(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT58(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT58(NAME, N, OP, FUNC, A, ...) __DOIT58(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT59(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT59(NAME, N, OP, FUNC, A, ...) __DOIT59(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT60(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT60(NAME, N, OP, FUNC, A, ...) __DOIT60(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT61(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT61(NAME, N, OP, FUNC, A, ...) __DOIT61(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT62(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT62(NAME, N, OP, FUNC, A, ...) __DOIT62(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
#define __DOIT63(NAME, N, OP, FUNC, A, ...) OP(NAME, FUNC(NAME, A, N), N, PASTE(_DOIT, N)(NAME, N, OP, FUNC, __VA_ARGS__, ))
#define _DOIT63(NAME, N, OP, FUNC, A, ...) __DOIT63(NAME, _predecessor(N), OP, FUNC, A, __VA_ARGS__)
